### ISSUE TITLE
Corriger: Code.php

### ISSUE THREAD

**Issue by ReinWired** [WebDevCF2m2020/intranet-cf2m#10]
#

- Le __construct existe dans MappingTableAbstract avec le mot-clef final donc on ne peut pas réécrire cette méthode dans la classe enfant Code
- La condition regarde si l'intitulé fait 5 caractères ou moins mais renvoie une erreur alors que cela est censé être valide !
- Penser à éviter de mettre une majuscule quand ce n'est pas une classe ($Ladescription)
- La condition regarde si la description fait 45 caractères ou moins mais renvoie une erreur alors que cela est censé être valide !

**Comment by mikhawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Faire le mapping de la table : lecode](https://trello.com/c/q3jGpVLX/35-faire-le-mapping-de-la-table-lecode)

**Comment by CHIHAB09** [comment]
update table

**Comment by ReinWired** [comment]
File corrected
