### ISSUE TITLE
Corriger model/droit

### ISSUE THREAD

**Issue by mikhawa** [WebDevCF2m2020/intranet-cf2m#13]
https://github.com/WebDevCF2m2020/intranet-cf2m/blob/main/model/Droit.php

`Line 82 to 85:  

60 or 5 ?

//checking lenght name is not superieur for 60 caratcters
        }else if (strlen($lintitule) >= 5){
            trigger_error("The lenght of your name cannot exceed 60 characters!!",E_USER_NOTICE);`

`Line 101

is empty (comment)

//checking is not empty
        if(empty($ladescription)){`

**Comment by mikhawa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Faire le mapping de la table : ledroit](https://trello.com/c/3uchp4Gj/36-faire-le-mapping-de-la-table-ledroit)

**Comment by CHIHAB09** [comment]
update table

**Comment by ReinWired** [comment]
File corrected
